# Generated by Django 4.2.1 on 2023-06-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('idAlmacen', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAlmacen', models.CharField(max_length=50)),
                ('direccionAlmacen', models.CharField(max_length=50)),
                ('telefonoAlmacen', models.CharField(max_length=50)),
                ('emailAlmacen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='almacen/static/img', verbose_name='Imagenes')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='almacen/static/img', verbose_name='Imagenes')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='almacen/static/img', verbose_name='Imagenes')),
                ('manualInstrucciones', models.FileField(blank=True, null=True, upload_to='almacen/static/docs', verbose_name='Documentos')),
                ('tipoEquipo', models.CharField(max_length=1000)),
                ('subtipoEquipo', models.CharField(max_length=1000)),
                ('numeroInventario', models.IntegerField(blank=True, null=True, verbose_name='Numero de Inventario')),
                ('mantenimientoLicitado', models.BooleanField(blank=True, null=True, verbose_name='Mantenimiento Licitado')),
                ('numeroMantenedor', models.IntegerField(blank=True, null=True, verbose_name='Numero de Mantenedor')),
                ('marca', models.CharField(max_length=1000, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=1000, verbose_name='Modelo')),
                ('anyoFabricacion', models.IntegerField(blank=True, null=True, verbose_name='Año de Fabricacion')),
                ('sn', models.CharField(max_length=1000, verbose_name='SN')),
                ('nref', models.CharField(max_length=1000, verbose_name='NREF')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion')),
                ('comentarios', models.CharField(max_length=1000, verbose_name='Comentarios')),
                ('estado', models.CharField(max_length=1000, verbose_name='Estado')),
                ('anyoCompra', models.IntegerField(blank=True, null=True, verbose_name='Año de Compra')),
                ('numExpContratacion', models.IntegerField(blank=True, null=True, verbose_name='Numero de Expediente de Contratacion')),
                ('tiquetsReferenciaMantenedor', models.IntegerField(blank=True, null=True, verbose_name='Tiquets de Referencia del Mantenedor')),
                ('tiquetsReferenciaMantUV', models.IntegerField(blank=True, null=True, verbose_name='Tiquets de Referencia del Mantenedor UV')),
                ('tiquetsRefTiquetingFLA', models.IntegerField(blank=True, null=True, verbose_name='Tiquets de Referencia del Tiqueting FLA')),
                ('otros', models.CharField(max_length=1000, verbose_name='Otros')),
                ('clinica', models.CharField(max_length=1000, verbose_name='Clinica')),
                ('ubicacion', models.CharField(max_length=1000, verbose_name='Ubicacion')),
            ],
        ),
    ]
