# Generated by Django 4.2.1 on 2023-06-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almacen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="clinica",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Clinica"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="comentarios",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Comentarios"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Descripcion"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="estado",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Estado"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="marca",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Marca"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="modelo",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Modelo"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nref",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="NREF"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="otros",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Otros"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="sn",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="SN"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="subtipoEquipo",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipoEquipo",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="ubicacion",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Ubicacion"
            ),
        ),
    ]
