# Generated by Django 4.2.1 on 2023-06-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alter_producto_clinica_alter_producto_comentarios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='idProducto',
            new_name='id',
        ),
    ]
