# Generated by Django 4.2.2 on 2023-06-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_alter_producto_tipoequipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='subtipoEquipo',
            field=models.TextField(blank=True, null=True, verbose_name='Subtipo de Equipo'),
        ),
    ]
