# Generated by Django 4.2.2 on 2023-06-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_alter_producto_subtipoequipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='numeroInventario',
            field=models.TextField(verbose_name='Numero de Inventario'),
        ),
    ]
