# Generated by Django 4.2.2 on 2023-06-15 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_alter_producto_numeroinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='anyoFabricacion',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año de Fabricacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numeroMantenedor',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Numero de Mantenedor'),
        ),
    ]
