# Generated by Django 4.2.2 on 2023-06-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0010_alter_producto_modelo_alter_producto_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nref',
            field=models.TextField(blank=True, null=True, verbose_name='NREF'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sn',
            field=models.TextField(verbose_name='SN'),
        ),
    ]
