# Generated by Django 4.2.2 on 2023-06-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0013_alter_producto_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.TextField(blank=True, null=True, verbose_name='Estado'),
        ),
    ]
