# Generated by Django 4.2.2 on 2023-06-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0018_alter_producto_tiquetsreferenciamantuv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tiquetsRefTiquetingFLA',
            field=models.TextField(blank=True, null=True, verbose_name='Tiquets de Referencia del Tiqueting FLA'),
        ),
    ]
