# Generated by Django 4.2.2 on 2023-06-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0019_alter_producto_tiquetsreftiquetingfla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='otros',
            field=models.TextField(blank=True, null=True, verbose_name='Otros'),
        ),
    ]
