# Generated by Django 3.2.19 on 2023-07-13 11:37

import almacen.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0021_alter_producto_clinica_alter_producto_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='departamento',
            field=models.TextField(blank=True, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='anyoCompra',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900, message='El año de compra debe ser entre 1900 y 2100.'), django.core.validators.MaxValueValidator(2100, message='El año de compra debe ser entre 1900 y 2100.')], verbose_name='Año de Compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='anyoFabricacion',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900, message='El año de fabricación debe ser entre 1900 y 2100.'), django.core.validators.MaxValueValidator(2100, message='El año de fabricación debe ser entre 1900 y 2100.')], verbose_name='Año de Fabricacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagenes'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagenes'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagenes'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='manualInstrucciones',
            field=models.FileField(blank=True, null=True, upload_to='docs', validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip']), almacen.models.validate_pdf_or_zip], verbose_name='Documentos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numeroMantenedor',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999, message='El valor no es correcto')], verbose_name='Numero de Mantenedor'),
        ),
    ]
